;COMPARE 30H WITH P2. IF IT IS LESS THEN SEND THE VALUE TO P1 AND IF IT IS GREATER THEN SEND THE VALUE TO P3
ORG 00H
MOV A, P2
CJNE A, #30H, L1  ;COMPARE AND JUMP P2 TO L1 IF P2 AND 30H ARE NOT EQUAL   
L1: JNC L2        ;JUMP IF NOT CARRY
MOV P1, A
SJMP L3
L2: MOV P3, A
SJMP L3
L3:NOP
END